net-mgmt/icinga-php-library: fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%WWWDIR%%/vendor/doctrine/deprecations/src/Deprecation.php
Error: Orphaned: %%WWWDIR%%/vendor/doctrine/deprecations/src/PHPUnit/VerifyDeprecations.php
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%WWWDIR%%/vendor/doctrine/deprecations/lib/Doctrine/Deprecations/Deprecation.php
Error: Missing: %%WWWDIR%%/vendor/doctrine/deprecations/lib/Doctrine/Deprecations/PHPUnit/VerifyDeprecations.php
===> Error: Plist issues found.