x11-fonts/nerd-fonts: fix pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: @dir %%FONTSDIR%%/0xProto
Error: Missing: @dir %%FONTSDIR%%/CascadiaMono
Error: Missing: @dir %%FONTSDIR%%/CommitMono
Error: Missing: @dir %%FONTSDIR%%/D2Coding
Error: Missing: @dir %%FONTSDIR%%/DepartureMono
Error: Missing: @dir %%FONTSDIR%%/GeistMono
Error: Missing: @dir %%FONTSDIR%%/IntelOneMono
Error: Missing: @dir %%FONTSDIR%%/IosevkaTermSlab
Error: Missing: @dir %%FONTSDIR%%/MartianMono
Error: Missing: @dir %%FONTSDIR%%/Monaspace
Error: Missing: @dir %%FONTSDIR%%/Recursive
Error: Missing: @dir %%FONTSDIR%%/UbuntuSans
Error: Missing: @dir %%FONTSDIR%%/ZedMono
===> Error: Plist issues found.