net-mgmt/icinga2: fix port build
```
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/%%ICINGA2USER%%2/libpgsql_shim.so.2.14.1
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: lib/%%ICINGA2USER%%2/libpgsql_shim.so.2.14.0
===> Error: Plist issues found.
```