deskutils/syncthingtray: Fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/SectionHeader.qml
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/ToolTipTrigger.qml