deskutils/syncthingtray: Fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/libc++utilities.so.5.35.0
Error: Orphaned: lib/libqtutilities.so.6.22.0
Error: Orphaned: lib/libsyncthingconnector.so.39
Error: Orphaned: lib/libsyncthingmodel.so.39
Error: Orphaned: lib/libsyncthingwidgets.so.39
Error: Orphaned: share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/FilterTextField.qml
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: lib/libc++utilities.so.5.34.2
Error: Missing: lib/libqtutilities.so.6.21.3
Error: Missing: lib/libsyncthingconnector.so.38
Error: Missing: lib/libsyncthingmodel.so.38
Error: Missing: lib/libsyncthingwidgets.so.38
===> Error: Plist issues found.