net-mgmt/icinga-php-library: Fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%WWWDIR%%/vendor/brick/math/src/Internal/CalculatorRegistry.php
Error: Orphaned: %%WWWDIR%%/vendor/symfony/polyfill-php84/Resources/stubs/ReflectionConstant.php
Error: Orphaned: %%WWWDIR%%/vendor/symfony/polyfill-php84/bootstrap82.php