Revert "ports-mgmt/poudriere-dsh2dsh: Update to 3.4.99.20260414"
Doesn't build on 14.4

src/libexec/poudriere/write_atomic/mktemp.c:125:18: error: use of undeclared identifier 'O_CLOFORK'
  125 |             O_CLOEXEC | O_CLOFORK)) != 0) {
      |                         ^
1 error generated.

This reverts commit bf6528ec3f007ac87c7ae425f9f10a55fbe465ec.