net-mgmt/icinga2: fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/%%ICINGA2USER%%2/libpgsql_shim.so.2.14.3
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: lib/%%ICINGA2USER%%2/libpgsql_shim.so.2.14.2