devel/tree-sitter-parsers: fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/libtree-sitter-ocaml-interface.so
Error: Orphaned: lib/libtree-sitter-ocaml-type.so