deskutils/syncthingtray: Fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/FilterTextField.qml
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.