textproc/enchant2: Fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: lib/enchant-2/enchant_hunspell.a
===> Error: Plist issues found.