net-mgmt/icingaweb2: fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%WWWDIR%%/phpstan-baseline-7x.neon
Error: Orphaned: %%WWWDIR%%/phpstan-baseline-8.0.neon
Error: Orphaned: %%WWWDIR%%/phpstan-baseline-8.1+.neon
Error: Orphaned: %%WWWDIR%%/phpstan-baseline-8x.neon
Error: Orphaned: %%WWWDIR%%/phpstan-baseline-by-php-version.php
Error: Orphaned: %%WWWDIR%%/phpstan-baseline-standard.neon
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%WWWDIR%%/phpstan-baseline.neon
===> Error: Plist issues found.