deskutils/syncthingtray: Fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/syncthingconnector/translations/syncthingconnector_fr_FR.qm
Error: Orphaned: share/syncthingmodel/translations/syncthingmodel_fr_FR.qm
Error: Orphaned: %%DATADIR%%/translations/syncthingtray_fr_FR.qm
Error: Orphaned: share/syncthingwidgets/translations/syncthingwidgets_fr_FR.qm