deskutils/syncthingtray: fix plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/metainfo/io.github.martchus.syncthingfileitemaction.metainfo.xml
Error: Orphaned: share/metainfo/io.github.martchus.syncthingplasmoid.metainfo.xml
Error: Orphaned: share/metainfo/io.github.martchus.syncthingtray.metainfo.xml
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/metainfo/syncthingfileitemaction.metainfo.xml
Error: Missing: share/metainfo/syncthingplasmoid.metainfo.xml
Error: Missing: share/metainfo/syncthingtray.metainfo.xml
===> Error: Plist issues found.