www/rss-bridge: Fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%WWWDIR%%/bridges/AuctionetBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/BazarakiBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/BruegelBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/ElektroARGOSBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/LeagueOfLegendsNewsBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/LinuxBlogBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/MinecraftBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/PaulGrahamBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/ShadertoyBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/SubstackProfileBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/TomsToucheBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/YouTubeFeedExpanderBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/ZonebourseBridge.php
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%WWWDIR%%/bridges/AnthropicBridge.php
Error: Missing: %%WWWDIR%%/bridges/CuriousCatBridge.php
Error: Missing: %%WWWDIR%%/bridges/FDroidBridge.php
Error: Missing: %%WWWDIR%%/bridges/OpenlyBridge.php
===> Error: Plist issues found.