net-mgmt/icinga-php-library: Fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%WWWDIR%%/asset/css/action-link-and-button-link.less
Error: Orphaned: %%WWWDIR%%/asset/css/suggestion-element.less
Error: Orphaned: %%WWWDIR%%/asset/static/font/icinga-icons/src/add-inside.svg
Error: Orphaned: %%WWWDIR%%/asset/static/font/icinga-icons/src/insert-group.svg
Error: Orphaned: %%WWWDIR%%/asset/static/font/icinga-icons/src/wrap.svg
Error: Orphaned: %%WWWDIR%%/vendor/doctrine/collections/docs/composer.json
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/Contract/DecorableFormElement.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/Contract/DecorationResult.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/Contract/DecoratorOptions.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/Contract/DecoratorOptionsInterface.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/Contract/DefaultFormElementDecoration.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/Contract/Form.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/Contract/FormDecoration.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/Contract/FormElementDecoration.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/Contract/FormElements.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/Contract/HtmlElementInterface.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/Contract/MutableHtml.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/FormDecoration/DecoratorChain.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/FormDecoration/DescriptionDecorator.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/FormDecoration/ErrorsDecorator.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/FormDecoration/FieldsetDecorator.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/FormDecoration/FormDecorationResult.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/FormDecoration/FormElementDecorationResult.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/FormDecoration/HtmlTagDecorator.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/FormDecoration/LabelDecorator.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/FormDecoration/RenderElementDecorator.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/html/src/FormDecoration/Transformation.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/sql/src/Test/SharedDatabases.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/web/src/Compat/FormDecorator/CheckboxDecorator.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/web/src/Compat/FormDecorator/DescriptionDecorator.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/web/src/Compat/FormDecorator/LabelDecorator.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/web/src/Compat/FormDecorator/PrimaryButtonDecorator.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/web/src/FormElement/SearchSuggestions.php
Error: Orphaned: %%WWWDIR%%/vendor/ipl/web/src/FormElement/SuggestionElement.php
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%WWWDIR%%/vendor/webmozart/assert/LICENSE
Error: Missing: %%WWWDIR%%/vendor/webmozart/assert/composer.json
Error: Missing: %%WWWDIR%%/vendor/webmozart/assert/src/Assert.php
Error: Missing: %%WWWDIR%%/vendor/webmozart/assert/src/InvalidArgumentException.php
Error: Missing: %%WWWDIR%%/vendor/webmozart/assert/src/Mixin.php
===> Error: Plist issues found.