deskutils/syncthingtray: fix build after update to 1.4.11
```
/wrkdirs/usr/ports/deskutils/syncthingtray/work/c++utilities/chrono/timespan.cpp:74:18: error: implicit instantiation of undefined template 'std::array<double, 4>'
    auto parts = std::array<double, 4>();
                 ^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
1 error generated.
```

Upstream fixed by
https://github.com/Martchus/cpp-utilities/commit/b8dff49c017488971bd9668227425ad8a98383ac