www/rss-bridge: fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%WWWDIR%%/bridges/ComickBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/FabBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/FanaticalBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/I4wifiBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/NasestrechaBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/UniverseTodayBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/WaggaCouncilBridge.php
Error: Orphaned: %%WWWDIR%%/bridges/WarhammerComBridge.php
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%WWWDIR%%/bridges/AskfmBridge.php
Error: Missing: %%WWWDIR%%/bridges/DansTonChatBridge.php
Error: Missing: %%WWWDIR%%/bridges/FirstLookMediaTechBridge.php
===> Error: Plist issues found.