net-mgmt/icingaweb2-module-grafana: fix check-plist
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%WWWDIR%%/Makefile
Error: Orphaned: %%WWWDIR%%/phpcs.xml
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%WWWDIR%%/doc/images/03-module_grafana_configuration01.png
Error: Missing: %%WWWDIR%%/doc/images/06-cog.png
Error: Missing: %%WWWDIR%%/doc/images/06-dashboard-panel-graphite-edit.png
Error: Missing: %%WWWDIR%%/doc/images/grafana-import-base-metrics-dashboard.png
Error: Missing: %%WWWDIR%%/doc/images/icingaweb2_grafana_screenshot_03.png
Error: Missing: %%WWWDIR%%/doc/images/icingaweb2_grafana_screenshot_04.png
===> Error: Plist issues found.