deskutils/syncthingtray: Fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/syncthingconnector/translations/syncthingconnector_ru_RU.qm
Error: Orphaned: share/syncthingmodel/translations/syncthingmodel_ru_RU.qm
Error: Orphaned: %%DATADIR%%/translations/syncthingtray_ru_RU.qm
Error: Orphaned: share/syncthingwidgets/translations/syncthingwidgets_ru_RU.qm