net-mgmt/icingadb: Fix pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%EXAMPLESDIR%%/schema/mysql/upgrades/1.4.9.sql
===> Error: Plist issues found.