security/keepassxc: Fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%DATADIR%%/translations/keepassxc_be.qm
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.