Revert "net-p2p/transmission-components: Update to 4.1.0-beta.3"
on/crypto-utils.cc:24:10: fatal error: 'crc32c/crc32c.h' file not found
   24 | #include <crc32c/crc32c.h>
      |          ^~~~~~~~~~~~~~~~~
1 error generated.

This reverts commit 831726a3b3559a4a2c764c86f2194d7500ca2bed.